backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Посты"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime"}
      - {label: "Описание", name: "description", widget: "text", required: false}
      - {label: "Изображение", name: "image", widget: "image", required: false}
      - {label: "Текст поста", name: "body", widget: "markdown"}
media_folder: "images/uploads"
public_folder: "/images/uploads"