backend:
  name: github
  repo: hextech14/hextech
  branch: main
  client_id: ВАШ_CLIENT_ID   # Вставьте ваш Client ID
  auth_type: pkce            # Ключевая настройка - обходит Identity

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Посты"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Текст поста", name: "body", widget: "markdown"}
