бэкэнд:
  имя: гитхаб
  репо: hextech14/hextech
  ветвь: основной
  идентификатор_клиента: Ov23liXgN87pkC7i6Npr
  тип_аутентификации: пкче
  открытая_авторизация: истинный

медиа_папка: "изображения/загрузки"
публичная_папка: "/изображения/загрузки"

коллекции:
  - имя: "посты"
    этикетка: "Посты"
    папка: "_посты"
    создавать: истинный
    слизень: "{{slug}}"
    поля:
      - {этикетка: "Заголовок", имя: "название", виджет: "струна"}
      - {этикетка: "Текст поста", имя: "тело", виджет: "разметка"}
